version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:20"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:40"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "security"
