import {describe,it,expect} from 'vitest';
import {archiveLinks,parseArchiveArticle} from './stonkletNewsArchive';
import {NEWS_FEEDS,NEWS_IDENTITIES,collectNewsItems} from './stonkletNewsResearch';
import map from './stonkletNewsSourceMap.json';
const now=Date.parse('2026-10-07T00:00:00Z');
const page=(data:object)=>`<script type="application/ld+json">${JSON.stringify(data)}</script>`;
describe('expanded discovery and archive review',()=>{
 it('maps every identity to official archives and two distinct editorial source targets',()=>{expect(map.identities).toHaveLength(NEWS_IDENTITIES.length);for(const i of map.identities){expect(i.officialArchive).toMatch(/^https:/);expect(new Set(i.industrySourceIds).size).toBeGreaterThanOrEqual(2);for(const id of i.industrySourceIds)expect(map.industry.some(s=>s.id===id)).toBe(true);}expect(NEWS_FEEDS.filter(f=>f.enabled).length).toBeLessThanOrEqual(100);expect(new Set(NEWS_FEEDS.map(f=>f.url)).size).toBe(NEWS_FEEDS.length);});
 it('accepts original article dates but never modified-only, future or expired dates',()=>{const data={'@type':'NewsArticle',headline:'Product launches',datePublished:'2026-02-04',articleBody:'The company launched a product.'};expect(parseArchiveArticle(page(data),'https://example.com/news',now)?.status).toBe('needs-review');for(const date of [undefined,'2026-12-01','2024-02-01'])expect(parseArchiveArticle(page({...data,datePublished:date,dateModified:'2026-10-06'}),'https://example.com/news',now)).toBeNull();});
 it('does not fetch external links, credentials, scripts or attacker canonical URLs',()=>{expect(archiveLinks('<a href="/news/a">a</a><a href="https://evil.example/x">x</a><a href="javascript:alert(1)">x</a><a href="https://u:p@example.com/x">x</a>','https://example.com/news')).toEqual(['https://example.com/news/a']);expect(parseArchiveArticle(page({'@type':'NewsArticle',headline:'X',datePublished:'2026-01-01',url:'https://evil.example/a'}),'https://example.com/a',now)).toBeNull();});
 it('retains earnings for evidence review without publishing unsupported positive claims',async()=>{const feed=NEWS_FEEDS.find(f=>f.id==='stock-tesla')!;const result=await collectNewsItems('<rss><item><title>Tesla reports quarterly financial results</title><link>https://finance.yahoo.com/news/results</link><pubDate>2026-09-30</pubDate><description>Revenue grew 10% but profit declined.</description></item></rss>',feed,new Date(now).toISOString());expect(result.items).toEqual([]);expect(result.reviews[0]?.reason).toBe('needs-evidence-review');});
 it('does not equate Tether stablecoin news with gold or positive chips with inverse funds',async()=>{const feed=NEWS_FEEDS.find(f=>f.id==='expanded-official-tether-gold')!;const result=await collectNewsItems('<rss><item><title>Tether launches a new USDT product</title><link>https://tether.io/news/usdt</link><pubDate>2026-09-30</pubDate></item></rss>',feed,new Date(now).toISOString());expect(result.items).toEqual([]);expect(result.reviews[0]?.reason).toBe('unmapped');});
});
