import {describe,it,expect} from "vitest";
import {legacyNews,sameNarrative,selectNews,sourceDomain, type NewsItem} from "./stonkletsNews";
import saved from "./stonkletsNewsPreview.json";
import {collectNewsItems,NEWS_FEEDS,NEWS_IDENTITIES,newsAssociations,qualifyingNarrative,STOCK_NEWS_SYMBOLS} from "../functions/_lib/stonkletNewsResearch";
import {STONKLETS_CATALOG} from "./stonkletsCatalog";
const now=Date.parse("2026-10-07T00:00:00Z");
const entries=saved.map(item=>legacyNews(item as never));
describe("news-first selection",()=>{
 it("uses registrable source domains without spoofed parent domains",()=>{expect(sourceDomain("https://blogs.microsoft.com/a")).toBe("microsoft.com");expect(sourceDomain("https://news.bbc.co.uk/a")).toBe("bbc.co.uk");expect(sourceDomain("https://microsoft.com.evil.example/a")).toBe("evil.example");expect(sourceDomain("javascript:alert(1)")).toBe("");});
 it("keeps hero stocks unique and upcoming histories independent of launch or quotes",()=>{const upcoming={...entries[0]!,id:"news-"+"f".repeat(24),pairId:"amazon"};expect(STONKLETS_CATALOG.find(e=>e.id==="amazon")?.launchStatus).toBe("prelaunch");expect(selectNews([...entries,upcoming],undefined,now)).toHaveLength(5);expect(selectNews([...entries,upcoming],"amazon",now)).toHaveLength(1);expect(selectNews(entries,"apple",now)).toHaveLength(2);expect("returns" in upcoming).toBe(false);});
 it("expires stories after eleven months, excludes future/withdrawn records, retains original dates",()=>{const entry=entries[0]!;expect(selectNews([entry],entry.pairId,Date.parse(entry.sources[0]!.publishedAt)+366*86400000)).toEqual([]);expect(selectNews([{...entry,withdrawnAt:"now"}],entry.pairId,now)).toEqual([]);expect(selectNews([entry],entry.pairId,0)).toEqual([]);});
 it("prefers an original source over syndication and sorts source dates newest first",()=>{const original=entries[0]!;const syndicated={...original,id:"syndicated",sourcePriority:1};const selected=selectNews([...entries,syndicated],original.pairId,now);expect(selected.some(e=>e.id==="syndicated")).toBe(false);expect(selected[0]!.sources[0]!.publishedAt>=selected[1]!.sources[0]!.publishedAt).toBe(true);});
 it("caps stock history at ten distinct narratives",()=>{const list=Array.from({length:15},(_,i)=>({...entries[0]!,id:`item${i}`,narrativeKey:`story${i}`}));expect(selectNews(list,list[0]!.pairId,now)).toHaveLength(10);});
});
describe("research coverage and evidence",()=>{
 it("provides stock-specific discovery with exact company association and original publication dates",async()=>{
  expect(Object.keys(STOCK_NEWS_SYMBOLS)).toHaveLength(43);
  const feed=NEWS_FEEDS.find(e=>e.id==="stock-tesla")!;
  const xml=`<rss><item><title>Tesla launches new battery production</title><link>https://finance.yahoo.com/news/tesla-battery.html</link><pubDate>2026-10-02</pubDate></item><item><title>Rivian launches new factory</title><link>https://finance.yahoo.com/news/rivian.html</link><pubDate>2026-10-02</pubDate><description>Tesla rival</description></item><item><title>Tesla launches another product</title><link>https://finance.yahoo.com/news/updated.html</link><updated>2026-10-06</updated></item><item><title>Tesla stock has 50% upside, analyst says</title><link>https://finance.yahoo.com/news/opinion.html</link><pubDate>2026-10-06</pubDate></item></rss>`;
  const result=await collectNewsItems(xml,feed,new Date(now).toISOString());
  expect(result.items).toHaveLength(1);expect(result.items[0]?.pairId).toBe("tesla");
  expect(result.items[0]?.sources[0]?.publishedAt).toBe("2026-10-02T00:00:00.000Z");
  expect(result.items[0]?.sources[0]?.publisher).toBe("Yahoo Finance");
 });
 it("deduplicates syndication without merging new numerical milestones",()=>{expect(sameNarrative("Apple launches iPhone 18 with new camera", "Apple launches iPhone 18 with new camera today")).toBe(true);expect(sameNarrative("Amazon sales grew 20 percent", "Amazon sales grew 30 percent")).toBe(false);});
 it("does not map passing company references or the generic word strategy",()=>{const feed=NEWS_FEEDS.find(e=>e.id==="bbc-business")!;expect(newsAssociations(feed,{...entries[0]!.sources[0]!,title:"New strategy launches for retail growth",excerpt:"Amazon was mentioned as a comparison."})).toEqual([]);});
 it("maps every catalog identity",()=>expect(NEWS_IDENTITIES.map(e=>e.pairId)).toEqual(STONKLETS_CATALOG.map(e=>e.id)));
 it("does not invent company-specific growth from sector evidence or invert leveraged exposure",()=>{const feed=NEWS_FEEDS.find(e=>e.id==="bbc-business")!;const source={...entries[0]!.sources[0]!,title:"US online shopping sales grew 20% year on year",excerpt:"Quarterly industry report."};const associations=newsAssociations(feed,source);expect(associations).toEqual([expect.objectContaining({pairId:"amazon",relation:"sector"})]);expect(associations[0]!.evidence).toContain("does not establish Amazon-specific");expect(newsAssociations(feed,{...source,title:"Semiconductor sales grew 20%"})).toEqual([]);expect(newsAssociations(feed,{...source,title:"Amazon online shopping sales grew 20%"})[0]?.relation).toBe("direct");});
 it("rejects negative, neutral, promotional or unsupported stories",()=>{for(const title of ["Company warns of record losses","New guide to growth","Company will report earnings","Company could launch a product","Sponsored: Company launches a product","Company launches new product but cuts guidance","Apple faces record fines","Company revenue grows despite profit plunge"]){expect(qualifyingNarrative({...entries[0]!.sources[0]!,title,excerpt:"",publishedAt:new Date(now).toISOString()},now),title).toBe(false);}});
 it("collects product news without any market metrics and enforces canonical hosts",async()=>{const feed=NEWS_FEEDS.find(e=>e.id==="official-microsoft")!;const xml=`<rss><item><title>Microsoft launches a new Copilot product</title><link>https://blogs.microsoft.com/product?utm_source=feed</link><pubDate>2026-09-20</pubDate></item><item><title>Microsoft launches other product</title><link>https://evil.example/story</link><pubDate>2026-09-20</pubDate></item></rss>`;const result=await collectNewsItems(xml,feed,new Date(now).toISOString());expect(result.items).toHaveLength(1);expect(result.items[0]!.sources[0]!.url).toBe("https://blogs.microsoft.com/product");expect(result.items[0]!.sourceDomain).toBe("microsoft.com");expect("returns" in result.items[0]!).toBe(false);});
});
