import{readFileSync,writeFileSync,mkdirSync,existsSync}from'node:fs';import{createHash}from'node:crypto';
import map from '../app/functions/_lib/stonkletNewsSourceMap.json';import{archiveLinks,parseArchiveArticle}from'../app/functions/_lib/stonkletNewsArchive';
const selected=process.argv.find(x=>x.startsWith('--pairs='))?.slice(8).split(',');if(selected?.some(p=>!map.identities.some(i=>i.pairId===p)))throw new Error('Unknown stock');
const targetMonth=process.argv.find(x=>x.startsWith('--month='))?.slice(8);if(targetMonth&&!/^20\d\d-(?:0[1-9]|1[0-2])$/.test(targetMonth))throw new Error('Expected YYYY-MM month');
const directory='.tmp/stonklets-archive-cache';mkdirSync(directory,{recursive:true});
let requests=0;const limit=200,now=Date.now();const reports:any[]=[],candidates:any[]=[];
async function get(url:string){const key=createHash('sha256').update(url).digest('hex');const path=`${directory}/${key}.json`;if(existsSync(path)){const cached=JSON.parse(readFileSync(path,'utf8'));if(now-cached.at<86400000)return cached.body;}
 if(requests>=limit)throw new Error('Run request cap reached');requests++;const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(8000),headers:{accept:'text/html, application/xml','user-agent':'10X Stonklets research contact@10x.meme'}});if(!r.ok){await r.body?.cancel();throw new Error(`HTTP ${r.status}`);}const reader=r.body?.getReader();if(!reader)throw new Error('Empty body');let body='',bytes=0;const decoder=new TextDecoder();try{while(true){const part=await reader.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>2000000)throw new Error('Body limit');body+=decoder.decode(part.value,{stream:true});}body+=decoder.decode();}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}writeFileSync(path,JSON.stringify({at:now,body}));return body;}
const queue=map.identities.filter(i=>!selected||selected.includes(i.pairId));
await Promise.all(Array.from({length:3},async()=>{while(queue.length){const entry=queue.shift()!;const report:any={pairId:entry.pairId,url:entry.officialArchive,checkedAt:new Date(now).toISOString(),parsed:0,errors:[]};try{const html=await get(entry.officialArchive);report.status='reachable';let discovered=archiveLinks(html,entry.officialArchive);const pages=discovered.filter(u=>/[?&](?:page|year)=|\/page\/\d|\/20\d\d\/?$/i.test(u)).slice(0,3);for(const page of pages)try{discovered.push(...archiveLinks(await get(page),page));}catch(e){report.errors.push({url:page,error:String(e)});}const links=[...new Set(discovered)].filter(u=>u!==entry.officialArchive&&/news|press|blog|20\d\d/i.test(new URL(u).pathname));
 const score=(url:string)=>(targetMonth&&url.replaceAll('/','-').includes(targetMonth)?10:0)+Number(/20\d\d/.test(url));const dated=links.sort((a,b)=>score(b)-score(a)).slice(0,4);
 for(const url of dated)try{const article=parseArchiveArticle(await get(url),url,now);if(article&&(!targetMonth||article.publishedAt.startsWith(targetMonth))){candidates.push({...article,pairId:entry.pairId,discoveredAt:new Date(now).toISOString()});report.parsed++;}}catch(e){report.errors.push({url,error:String(e)});}
 }catch(e){report.status='unavailable';report.errors.push({url:entry.officialArchive,error:String(e)});}reports.push(report);}}));
const oldReview=existsSync('.tmp/stonklets-archive-review.json')?JSON.parse(readFileSync('.tmp/stonklets-archive-review.json','utf8')):{candidates:[]};const mergedCandidates=[...new Map([...oldReview.candidates,...candidates].map((c:any)=>[c.pairId+':'+c.url,c])).values()];
const output={checkedAt:new Date(now).toISOString(),requests,limit,notes:'Original datePublished only. Cached 24h. At most three linked archive pages and four article pages per issuer per run. Optional --month prioritizes dated links and filters candidates. Candidates require human evidence/identity/duplicate review; never auto-published.',sources:reports,candidates:mergedCandidates};
const previous=existsSync('docs/stonklets-news-archive-checks.json')?JSON.parse(readFileSync('docs/stonklets-news-archive-checks.json','utf8')):{sources:[],candidates:[]};const mergedSources=[...new Map([...previous.sources,...reports].map((s:any)=>[s.pairId,s])).values()];
writeFileSync('docs/stonklets-news-archive-checks.json',JSON.stringify({...output,sources:mergedSources,candidates:mergedCandidates.map(({evidence,...rest})=>({...rest,evidenceCharacters:evidence.length}))},null,2)+'\n');writeFileSync('.tmp/stonklets-archive-review.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({requests,sources:reports.length,reachable:reports.filter(r=>r.status==='reachable').length,candidates:candidates.length}));
