import {readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createRequire}from'node:module';const {getDomain}=createRequire(new URL('../app/package.json',import.meta.url))('tldts');
import{fetchNewsFeed,parseNewsFeed,type NewsFeed}from'../app/functions/_lib/stonkletNewsResearch';
import{STONKLETS_BY_ID}from'../app/shared/stonkletsCatalog';
const map=JSON.parse(readFileSync('app/functions/_lib/stonkletNewsSourceMap.json','utf8'));
const candidates:NewsFeed[]=[...map.identities.filter((s:any)=>s.officialFeedCandidate).map((s:any)=>({id:`expanded-official-${s.pairId}`,publisher:STONKLETS_BY_ID.get(s.pairId)!.stock.name,owner:STONKLETS_BY_ID.get(s.pairId)!.stock.name,url:s.officialFeedCandidate,pairIds:[s.pairId],priority:0})),...map.industry.filter((s:any)=>s.feedCandidate).map((s:any)=>({id:`industry-${s.id}`,publisher:s.publisher,owner:s.publisher,url:s.feedCandidate,pairIds:s.pairIds,priority:1}))].map(s=>({...s,hosts:[new URL(s.url).hostname],requireIdentity:s.pairIds.includes('tether-gold')&&s.priority===0,enabled:false,method:'public-rss'}));
const results:any[]=[];const pending=[...candidates];
await Promise.all(Array.from({length:4},async()=>{while(pending.length){const f=pending.shift()!;try{const r=await fetchNewsFeed(f);const hosts=[...new Set([...r.xml.matchAll(/https:\/\/([^/\s<>"']+)/g)].map(m=>m[1]!).filter(h=>getDomain(h)===getDomain(new URL(f.url).hostname)))];f.hosts=hosts;const count=parseNewsFeed(r.xml,f,new Date().toISOString()).length;results.push({feed:{...f,enabled:count>0},status:r.status,datedArticles:count,checkedAt:new Date().toISOString()});}catch(e){results.push({feed:f,error:String(e),checkedAt:new Date().toISOString()});}}}));
mkdirSync('docs',{recursive:true});writeFileSync('docs/stonklets-news-feed-checks.json',JSON.stringify(results,null,2)+'\n');
writeFileSync('.tmp/stonklets-news-verified-feeds.json',JSON.stringify(results.filter(r=>r.feed.enabled).map(r=>r.feed),null,2)+'\n');console.log(JSON.stringify(results.map(r=>({id:r.feed.id,articles:r.datedArticles,error:r.error}))));
